### ISSUE TITLE
Gem5 core dumped

### ISSUE THREAD

**Issue by swb1234554321** [cmlasu/ccf#1]
Hi!
After successfully install the ccd tool following the command './install', I tried to run gem5 with the example executable in 'basicmath13'. However, gem5 complains as the following info:

_gem5 Simulator System.  http://gem5.org
gem5 is copyrighted software; use the --copyright option for details.

gem5 compiled Nov 20 2018 18:15:47
gem5 started Nov 20 2018 20:05:10
gem5 executing on ubuntu
command line: ./build/ARM/gem5.opt ./configs/example/se_hetro.py -n 2 --cpu-type atomic -c ./../work/benchmarks/MiBench/basicmath-CCF/basicmath13 (copy)/basicmath_small
Global frequency set at 1000000000000 ticks per second

MASTER system_port binds to SLAVE system.membus.slave[0]

MASTER system.membus.master[0] binds to SLAVE system.mem_ctrls.port

MASTER system.cpu0.icache_port binds to SLAVE system.membus.slave[1]

MASTER system.cpu0.dcache_port binds to SLAVE system.membus.slave[2]

MASTER system.cpu0.dtb.walker.dma binds to SLAVE system.membus.slave[4]

MASTER system.cpu0.itb.walker.dma binds to SLAVE system.membus.slave[3]

MASTER system.cpu1.icache_portdcache_port binds to SLAVE system.membus.slave[5]

MASTER system.cpu1.dcache_portdcache_port binds to SLAVE system.membus.slave[6]

MASTER system.cpu1.dtb.walker.dma binds to SLAVE system.membus.slave[8]

MASTER system.cpu1.itb.walker.dma binds to SLAVE system.membus.slave[7]
0: system.remote_gdb.listener: listening for remote gdb #0 on port 7000
0: system.remote_gdb.listener: listening for remote gdb #1 on port 7001
**** REAL SIMULATION ****
info: Entering event queue @ 0.  Starting simulation...
warn: ignoring syscall set_tid_address(1, 901224, ...)
warn: ignoring syscall set_robust_list(12, 901232, ...)
warn: ignoring syscall rt_sigaction(3204447088, 32, ...)
info: Increasing stack size by one page.
panic: Page table fault when accessing virtual address 0
 @ cycle 42967264
[invoke:build/ARM/sim/faults.cc, line 70]
Memory Usage: 42967264 KBytes
Program aborted at cycle 3945500
Aborted (core dumped)
swb@ubuntu:/media/swb/lab/ccf-master/gem5$ make clean
make: *** No rule to make target `clean'.  Stop.
swb@ubuntu:/media/swb/lab/ccf-master/gem5$ make
make: *** No targets specified and no makefile found.  Stop.
swb@ubuntu:/media/swb/lab/ccf-master/gem5$ make
make: *** No targets specified and no makefile found.  Stop.
swb@ubuntu:/media/swb/lab/ccf-master/gem5$ ./build/ARM/gem5.opt ./configs/example/se_hetro.py -n 2 --cpu-type atomic -c ./../work/benchmarks/MiBench/basicmath-CCF/basicmath13\ \(copy\)/basicmath_small 
gem5 Simulator System.  http://gem5.org
gem5 is copyrighted software; use the --copyright option for details.

gem5 compiled Nov 20 2018 18:15:47
gem5 started Nov 20 2018 20:07:00
gem5 executing on ubuntu
command line: ./build/ARM/gem5.opt ./configs/example/se_hetro.py -n 2 --cpu-type atomic -c ./../work/benchmarks/MiBench/basicmath-CCF/basicmath13 (copy)/basicmath_small
Global frequency set at 1000000000000 ticks per second

MASTER system_port binds to SLAVE system.membus.slave[0]

MASTER system.membus.master[0] binds to SLAVE system.mem_ctrls.port

MASTER system.cpu0.icache_port binds to SLAVE system.membus.slave[1]

MASTER system.cpu0.dcache_port binds to SLAVE system.membus.slave[2]

MASTER system.cpu0.dtb.walker.dma binds to SLAVE system.membus.slave[4]

MASTER system.cpu0.itb.walker.dma binds to SLAVE system.membus.slave[3]

MASTER system.cpu1.icache_portdcache_port binds to SLAVE system.membus.slave[5]

MASTER system.cpu1.dcache_portdcache_port binds to SLAVE system.membus.slave[6]

MASTER system.cpu1.dtb.walker.dma binds to SLAVE system.membus.slave[8]

MASTER system.cpu1.itb.walker.dma binds to SLAVE system.membus.slave[7]
0: system.remote_gdb.listener: listening for remote gdb #0 on port 7000
0: system.remote_gdb.listener: listening for remote gdb #1 on port 7001
**** REAL SIMULATION ****
info: Entering event queue @ 0.  Starting simulation...
warn: ignoring syscall set_tid_address(1, 901224, ...)
warn: ignoring syscall set_robust_list(12, 901232, ...)
warn: ignoring syscall rt_sigaction(3204447088, 32, ...)
info: Increasing stack size by one page.
panic: Page table fault when accessing virtual address 0
 @ cycle 42967264
[invoke:build/ARM/sim/faults.cc, line 70]
Memory Usage: 42967264 KBytes
Program aborted at cycle 3945500
Aborted (core dumped)_

The basic environment is Ubuntu 14.04 (VMware virtual machine, 8GB memory & 8 cores cpu), gcc 4.8.5 and python 2.7. I have tried gcc 4.7 and 5.4 but no luck.

Thank you very much for any help, I have stuck at this point for several days.

**Comment by ccf-Adam** [comment]
hi,sir,
What means '$./install' in  the  "How to work"? How should I install ccf ? In the terminal , input '/home/name/ccf/install' ,then input '/home/name/scripts/install_dependecies' ,is it right? But, installation has failed. Could you help me? Thank you.

**Comment by cmlasu** [comment]
Hi @ccf-Adam ,

Let's say you cloned the repo at `path="/home/name"`
Change your working directory to repo.
`cd  /home/name/ccf  
`
Then, you should ensure that installation scripts have execution permissions. You may provide it through:
` chmod +x install`
`chmod +x scripts/install_dependencies `

Then, you can execute the installation script by typing -
`./install`

If you find that somehow a specific package is not being installed properly (e.g., due to any version mismatch), you may install the package manually. Info about required packages can be found in the script `path/ccf/scripts/install_dependecies`
