### ISSUE TITLE
where is the implement code about CGRA in gem5?

### ISSUE THREAD

**Issue by meton-robean** [cmlasu/ccf#2]
As you said, your simulation platform is built in gem5, where you have modeled the CGRA as a separate core coupled  to ARM Cortex like processor. where is the implement code about CGRA in gem5 dir? I can not find it~ can you help me , thanks!

**Comment by shail-dave** [comment]
Hi, please find it at: /path/to/ccf/gem5/src/cpu/atomiccgra. Thanks.
